sonar.projectKey=AnushGurung11_Media-Player
sonar.organization=anushgurung11

sonar.sources=backend,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.js,**/coverage/**,**/.husky/**,**/monitoring/**

sonar.sourceEncoding=UTF-8